# Generated by Django 3.2.6 on 2022-05-29 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dialog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('members', models.TextField()),
                ('file', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('category', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('surname', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=100)),
                ('avatar', models.CharField(max_length=500)),
                ('login', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=200)),
                ('token', models.CharField(max_length=512)),
                ('fridge', models.TextField()),
                ('forums', models.TextField()),
                ('starredRecipes', models.TextField()),
                ('bannedRecipes', models.TextField()),
                ('starredIngredients', models.TextField()),
                ('bannedIngredients', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('likes', models.IntegerField()),
                ('comments', models.TextField()),
                ('category', models.TextField()),
                ('steps', models.TextField()),
                ('ingredients', models.TextField()),
                ('time', models.IntegerField()),
                ('calories', models.IntegerField()),
                ('proteins', models.IntegerField()),
                ('carbs', models.IntegerField()),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.user')),
            ],
        ),
        migrations.CreateModel(
            name='Forum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('members', models.TextField()),
                ('file', models.TextField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.user')),
            ],
        ),
    ]
