# Generated by Django 3.2.6 on 2022-06-03 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20220602_1757'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ownRecipes',
            field=models.TextField(default=''),
        ),
    ]
