# Generated by Django 3.2.6 on 2022-06-09 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_user_ownrecipes'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TextMessages',
            new_name='TextMessage',
        ),
        migrations.RemoveField(
            model_name='user',
            name='login',
        ),
        migrations.AlterField(
            model_name='recipe',
            name='calories',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(default=None, upload_to='[]/images'),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(upload_to='D:\\ПИТОНН\\CookHelper\\cookhelper\\media/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='nickname',
            field=models.CharField(default='', max_length=100),
        ),
    ]
