# Generated by Django 3.2.6 on 2022-06-10 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_user_nickname'),
    ]

    operations = [
        migrations.AddField(
            model_name='forum',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
