# Generated by Django 3.2.6 on 2022-06-11 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20220611_2211'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='private',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='recoveryCode',
            field=models.CharField(default='', max_length=5),
        ),
        migrations.AlterField(
            model_name='user',
            name='code',
            field=models.CharField(default='', max_length=6),
        ),
    ]
