# Generated by Django 3.2.6 on 2022-06-14 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20220612_0156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='', upload_to='D:\\ПИТОНН\\CookHelper\\cookhelper\\media//users/<built-in function id>'),
        ),
    ]
