# Generated by Django 3.2.6 on 2022-06-14 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='', upload_to='D:\\ПИТОНН\\CookHelper\\cookhelper\\media//users/<django.db.models.fields.CharField>'),
        ),
    ]
